---
- name: Exercise for setting up a web server in an EC2
  hosts: all
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
  roles:
    - setup
